version: '3.9'
services:
    rabbitmq:
        container_name: aofg_rabbit
        image: rabbitmq:3-management-alpine
        ports:
            - '127.0.0.1:5672:5672'
            - '127.0.0.1:15672:15672'

    postgres:
        container_name: aofg_postgres
        image: postgres:16
        environment:
            POSTGRES_DB: 'aofg'
            POSTGRES_USER: 'user'
            POSTGRES_PASSWORD: 'password'
        ports:
            - '127.0.0.1:5432:5432'
        volumes:
            - postgres:/var/lib/postgresql/data

volumes:
    postgres:
        driver: local
    redis:
        driver: local
